# This workflow will run build the project w/ docker compose, put it up and down, and if all passed, push to dockerhub.

name: Docker Compose

on:
  push:
    branches: [ deployment ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker/docker-compose.yml"
          down-flags: "--volumes"
          services: |
            app
      - run: docker compose push
